In [1]:
import numpy as np


In [2]:
list=[1,2,3]
list

[1, 2, 3]

In [3]:
np.array(list)

array([1, 2, 3])

In [4]:
matrix=[[1,2,3],[3,2,1]]
matrix

[[1, 2, 3], [3, 2, 1]]

In [5]:
np.matrix(matrix)

matrix([[1, 2, 3],
        [3, 2, 1]])

In [6]:
np.array(matrix)

array([[1, 2, 3],
       [3, 2, 1]])

In [7]:
matrix=[[1,2,3], [2,3,4]]
np.array(matrix)

array([[1, 2, 3],
       [2, 3, 4]])

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.two(3,3)


AttributeError: module 'numpy' has no attribute 'two'

In [11]:
np.ones(3,3)

TypeError: Cannot interpret '3' as a data type

In [13]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
np.linespace(1,3,9)

AttributeError: module 'numpy' has no attribute 'linespace'

In [15]:
np.linespace((1,3,9))

AttributeError: module 'numpy' has no attribute 'linespace'

In [16]:
np.linspace(1,3,9)

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  ])

In [17]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [18]:
np.eyes(3,3)

AttributeError: module 'numpy' has no attribute 'eyes'

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
arr=np.zeros[10,10]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [21]:
arr=np.zeros(10,10)

TypeError: Cannot interpret '10' as a data type

In [22]:
arr=np.zeros((10,10))

In [23]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
arr2=arr.shape[1]

In [25]:
arr2

10

In [27]:
arro=np.arange((1,100,10))

TypeError: arange: scalar arguments expected instead of a tuple.

In [28]:
for i in range(0,100):
    pip=np.array[i]=i
pip

TypeError: 'builtin_function_or_method' object does not support item assignment

In [29]:
q=np.arange((1,10,2))
q

TypeError: arange: scalar arguments expected instead of a tuple.

In [32]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr.shape[1]

IndexError: tuple index out of range

In [35]:
length=arr.shape[0]

In [36]:
length


9

In [39]:
arr=np.linspace(1,100,100)

In [40]:
arr

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [41]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
pi = 3.14159 # approximate
diameter = 3


In [44]:
radius=diameter/2
radius

1.5

In [46]:
area=pi*radius*radius

In [47]:
area

7.068577499999999

In [48]:
a=[1,2,3]
b=[4,5,6]
a
b

[4, 5, 6]

In [49]:
a

[1, 2, 3]

In [50]:
a,b=b,a

In [51]:
a

[4, 5, 6]

In [52]:
b

[1, 2, 3]

In [58]:
# yet another type of Python object, like int or float.
a = [1, 2, 3]
b = [3, 2, 1]
q2.store_original_ids(a,b)
    

# Check your answer
q2.check()

NameError: name 'q2' is not defined